import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import roomsRouter from "./rooms";
import guestsRouter from "./guests";
import messagesRouter from "./messages";
import energyRouter from "./energy";
import teleportRouter from "./teleport";
import transactionsRouter from "./transactions";
import settingsRouter from "./settings";
import statsRouter from "./stats";
import activityRouter from "./activity";
import vipRouter from "./vip";
import rentalsRouter from "./rentals";
import tipsRouter from "./tips";
import oracleRouter from "./oracle";
import sponsoredRouter from "./sponsored";
import referralsRouter from "./referrals";
import premiumMessagesRouter from "./premium-messages";
import boostsRouter from "./boosts";
import incomeRouter from "./income";
import analyticsRouter from "./analytics";
import achievementsRouter from "./achievements";
import eventsRouter from "./events";
import chatRouter from "./chat";
import hiveMindRouter from "./hive-mind";
import oracleAiRouter from "./oracle-ai";
import securityRouter from "./security";
import xrpRouter from "./xrp";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/lounge/rooms", roomsRouter);
router.use("/guests", guestsRouter);
router.use("/messages", messagesRouter);
router.use("/energy", energyRouter);
router.use("/teleport", teleportRouter);
router.use("/transactions", transactionsRouter);
router.use("/settings", settingsRouter);
router.use("/stats", statsRouter);
router.use("/activity", activityRouter);
router.use("/memberships", vipRouter);
router.use("/rentals", rentalsRouter);
router.use("/tips", tipsRouter);
router.use("/oracle", oracleRouter);
router.use("/sponsored-rooms", sponsoredRouter);
router.use("/referrals", referralsRouter);
router.use("/premium-messages", premiumMessagesRouter);
router.use("/leaderboard-boosts", boostsRouter);
router.use("/income", incomeRouter);
router.use("/analytics", analyticsRouter);
router.use("/achievements", achievementsRouter);
router.use("/events", eventsRouter);
router.use("/chat", chatRouter);
router.use("/hive-mind", hiveMindRouter);
router.use("/oracle", oracleAiRouter);
router.use("/security", securityRouter);
router.use("/xrp", xrpRouter);

export default router;
