kind = "mobile"
previewPath = "/mobile/"
title = "Quantum Lounge Mobile"
version = "1.0.0"
id = "artifacts/quantum-lounge-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/mobile/" ]
localPort = 21353

[services.development]
run = "pnpm --filter @workspace/quantum-lounge-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/quantum-lounge-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/quantum-lounge-mobile", "run", "serve" ]

[services.env]
PORT = "21353"
BASE_PATH = "/mobile/"
